// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTsS35RleRGVVIg7QYKTIekjzg2IBQuV0',
    appId: '1:326663640766:web:19fd6dabab3fa96cda30ef',
    messagingSenderId: '326663640766',
    projectId: 'nabla-3560b',
    authDomain: 'nabla-3560b.firebaseapp.com',
    storageBucket: 'nabla-3560b.appspot.com',
    measurementId: 'G-BET6K4PRDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0DksBTc9n8-hzwIWRnpVfzCEUXOd87o',
    appId: '1:326663640766:android:ffbeb7c8e9bf1e17da30ef',
    messagingSenderId: '326663640766',
    projectId: 'nabla-3560b',
    storageBucket: 'nabla-3560b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6e7rFCs7u6Ryxf7tVszLhW9WgYO5Tmmc',
    appId: '1:326663640766:ios:48def7fcc1313f5ada30ef',
    messagingSenderId: '326663640766',
    projectId: 'nabla-3560b',
    storageBucket: 'nabla-3560b.appspot.com',
    iosBundleId: 'com.example.nablagreier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6e7rFCs7u6Ryxf7tVszLhW9WgYO5Tmmc',
    appId: '1:326663640766:ios:48def7fcc1313f5ada30ef',
    messagingSenderId: '326663640766',
    projectId: 'nabla-3560b',
    storageBucket: 'nabla-3560b.appspot.com',
    iosBundleId: 'com.example.nablagreier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTsS35RleRGVVIg7QYKTIekjzg2IBQuV0',
    appId: '1:326663640766:web:19b75f9ca6c9fb8eda30ef',
    messagingSenderId: '326663640766',
    projectId: 'nabla-3560b',
    authDomain: 'nabla-3560b.firebaseapp.com',
    storageBucket: 'nabla-3560b.appspot.com',
    measurementId: 'G-7B4GDTF8WK',
  );
}
